import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { FruitListComponent } from './fruit/fruit-list/fruit-list.component';
import { VisionUploadComponent } from './vision-upload/vision-upload.component';
import { GalleryComponent } from './gallery/gallery.component';
import { ExploreComponent } from './explore/explore.component';
import { RecommendComponent } from './recommend/recommend.component';
import { RecipeComponent } from './recipe/recipe.component';
import { MealPlannerComponent } from './meal-planner/meal-planner.component';
import { FruitCultureComponent } from './fruit-culture/fruit-culture.component';
import { KnowledgeGraphComponent } from './knowledge-graph/knowledge-graph.component';
import { BarcodeScannerComponent } from './barcode-scanner/barcode-scanner.component';
import { HealthPlatformComponent } from './health-platform/health-platform.component';
import { PremiumComponent } from './premium/premium.component';

export const routes: Routes = [
	{ path: '', component: HomeComponent },
	{ path: 'fruits', component: FruitListComponent },
	{ path: 'vision', component: VisionUploadComponent },
	{ path: 'gallery', component: GalleryComponent },
	{ path: 'explore/:name', component: ExploreComponent },
	{ path: 'recommend', component: RecommendComponent },
	{ path: 'recipes', component: RecipeComponent },
	{ path: 'meal-planner', component: MealPlannerComponent },
	{ path: 'fruit-culture', component: FruitCultureComponent },
	{ path: 'knowledge-graph', component: KnowledgeGraphComponent },
	{ path: 'barcode', component: BarcodeScannerComponent },
	{ path: 'health-platform', component: HealthPlatformComponent },
	{ path: 'premium', component: PremiumComponent }
];
